name: time_keeper
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Flutter official icon set
  cupertino_icons: ^1.0.8

  # Flutter official SQLite bindings
  sqflite: ^2.3.3

  # Flutter official path provider (for app directories)
  path_provider: ^2.1.3

  # Flutter geolocation plugin
  geolocator: ^11.0.0

  # Flutter internationalization/date formatting
  intl: ^0.19.0

  # Flutter CSV parser
  csv: ^5.1.1

  # Flutter system notifications
  flutter_local_notifications: ^17.2.1

  # Flutter secure storage (used by manager/org services)
  flutter_secure_storage: ^9.2.2

  # Dart cryptography utilities
  crypto: ^3.0.3

  # Dart UUID generator
  uuid: ^4.4.2

  device_info_plus: ^11.0.0

  image_picker: ^1.1.2
  # Calendar Generator - Suong T
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
